import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from src.recommendation import recommend_courses_for_user

# --- App Configuration ---
st.set_page_config(page_title="EduPro Analytics", page_icon="🎓", layout="wide")


# --- Load Data Cache ---
@st.cache_data
def load_app_data():
    base_dir = "z:/Documents/UnifiedMentor/student_segmentation/data"

    courses = pd.read_csv(f"{base_dir}/Courses.csv")
    transactions = pd.read_csv(f"{base_dir}/Transactions.csv")
    profiles = pd.read_csv(f"{base_dir}/processed/learner_profiles_with_clusters.csv")
    features = pd.read_csv(
        f"{base_dir}/processed/clustering_features_with_clusters.csv"
    )

    # Define cluster semantic names (Assume 2 clusters based on earlier analysis: Explorers vs Specialists)
    # This is a simplified assignment based on common e-learning groupings
    cluster_names = {0: "General Explorers", 1: "Focused Specialists"}
    if 2 in profiles["Cluster"].unique():
        cluster_names[2] = "High-Value Learners"

    profiles["SegmentName"] = profiles["Cluster"].map(cluster_names)

    return courses, transactions, profiles, features


courses, transactions, profiles, features = load_app_data()

# --- Title and Sidebar ---
st.title("🎓 EduPro Analytics & Recommendation Engine")
st.sidebar.header("Navigation")
menu = [
    "Dashboard Overview",
    "Learner Explorer & Recommendations",
    "Segment Comparison",
]
choice = st.sidebar.radio("Go to:", menu)

# --- View 1: Dashboard Overview ---
if choice == "Dashboard Overview":
    st.header("Cluster Visualization Dashboard")
    st.markdown("Analyze the macro-level segments generated by our K-Means model.")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Segment Distribution")
        seg_counts = profiles["SegmentName"].value_counts().reset_index()
        seg_counts.columns = ["Segment", "Count"]
        fig_pie = px.pie(
            seg_counts,
            names="Segment",
            values="Count",
            hole=0.4,
            title="Users per Segment",
        )
        st.plotly_chart(fig_pie, use_container_width=True)

    with col2:
        st.subheader("Key Metrics per Segment")
        metrics = (
            profiles.groupby("SegmentName")
            .agg(
                AvgSpending=("AverageSpending", "mean"),
                AvgEngagement=("TotalCoursesEnrolled", "mean"),
            )
            .reset_index()
        )
        fig_bar = px.bar(
            metrics,
            x="SegmentName",
            y=["AvgSpending", "AvgEngagement"],
            barmode="group",
            title="Spending vs Engagement",
        )
        st.plotly_chart(fig_bar, use_container_width=True)

    st.subheader("Cluster Characteristics (PCA View)")
    st.markdown("A 2D projection of learner profiles to visualize cluster separation.")
    # Assuming the first two features mostly capture the variance or utilizing directly for simplicity in preview
    if (
        "TotalCoursesEnrolled" in features.columns
        and "AverageSpending" in features.columns
    ):
        fig_scatter = px.scatter(
            profiles,
            x="TotalCoursesEnrolled",
            y="AverageSpending",
            color="SegmentName",
            title="Engagement vs Spending Cluster Mapping",
            opacity=0.7,
        )
        st.plotly_chart(fig_scatter, use_container_width=True)

# --- View 2: Learner Explorer ---
elif choice == "Learner Explorer & Recommendations":
    st.header("Learner Profile & Recommendations")

    selected_user = st.sidebar.selectbox("Select User ID:", profiles["UserID"].unique())
    user_data = profiles[profiles["UserID"] == selected_user].iloc[0]

    st.subheader(f"Profile: {user_data['UserName']}")
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Segment", user_data["SegmentName"])
    col2.metric("Total Courses", int(user_data["TotalCoursesEnrolled"]))
    col3.metric("Avg Course Rating", f"{user_data['AverageCourseRating']:.2f}")
    col4.metric("Total Spends", f"${user_data['TotalSpending']:.2f}")

    st.markdown("---")
    st.subheader("Personalized Course Recommendations")

    # Recommendation Filters
    f_col1, f_col2 = st.columns(2)
    level_filter = f_col1.selectbox(
        "Filter by Level", ["All"] + list(courses["CourseLevel"].unique())
    )
    cat_filter = f_col2.selectbox(
        "Filter by Category", ["All"] + list(courses["CourseCategory"].unique())
    )

    lvl = None if level_filter == "All" else level_filter
    cat = None if cat_filter == "All" else cat_filter

    with st.spinner("Generating smart recommendations..."):
        recs = recommend_courses_for_user(
            selected_user,
            courses,
            profiles,
            transactions,
            top_n=5,
            filter_level=lvl,
            filter_category=cat,
        )

    if not recs.empty:
        st.dataframe(
            recs[
                [
                    "CourseID",
                    "CourseName",
                    "CourseCategory",
                    "CourseLevel",
                    "CourseRating",
                    "RecommendationScore",
                ]
            ],
            use_container_width=True,
        )
    else:
        st.info(
            "No new recommendations found matching the criteria (Learner may have completed all relevant courses in this filter)."
        )

# --- View 3: Segment Comparison ---
elif choice == "Segment Comparison":
    st.header("Segment Comparison Panels")
    st.markdown("Deep dive into the differences between Learner segments.")

    # Radar chart for average scaled features
    st.subheader("Behavioral Fingerprint")
    radar_features = [
        "TotalCoursesEnrolled",
        "EnrollmentFrequency",
        "UniqueCategoriesEnrolled",
        "AverageSpending",
        "AverageCourseRating",
        "DiversityScore",
        "LearningDepthIndex",
    ]

    avg_feats = profiles.groupby("SegmentName")[radar_features].mean().reset_index()

    fig = go.Figure()
    for _, row in avg_feats.iterrows():
        fig.add_trace(
            go.Scatterpolar(
                r=row[radar_features].values,
                theta=radar_features,
                fill="toself",
                name=row["SegmentName"],
            )
        )

    fig.update_layout(
        polar=dict(
            radialaxis=dict(
                visible=True, range=[0, avg_feats[radar_features].max().max() + 1]
            )
        ),
        showlegend=True,
    )
    st.plotly_chart(fig, use_container_width=True)

    st.subheader("Key Demographic Insights")
    age_boxplot = px.box(
        profiles,
        x="SegmentName",
        y="Age",
        color="SegmentName",
        title="Age Distribution by Segment",
    )
    st.plotly_chart(age_boxplot, use_container_width=True)
